# Generated by Django 3.0.3 on 2020-08-13 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(blank=True, max_length=100)),
                ('docintro', models.CharField(blank=True, max_length=300)),
                ('doctitle', models.CharField(blank=True, max_length=100)),
                ('doctext', models.TextField()),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lasttime', models.DateTimeField(auto_now=True)),
                ('stat', models.IntegerField(default=0)),
                ('admindoc', models.IntegerField(default=0)),
                ('deletetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
