# Generated by Django 3.0.3 on 2020-08-14 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Table', '0002_auto_20200813_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Table.File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
