# Generated by Django 3.0.3 on 2020-08-16 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Table', '0003_collectlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='isedit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='lastauthor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
