# Generated by Django 3.0.3 on 2020-08-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0006_file_groupnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='docintro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='doctitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
